runtime: nodejs10

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 1

handlers:
  - url: /static
    static_dir: dist/static
  - url: /manifest.json
    static_files: manifest.json
    upload: manifest.json
  - url: /(.*\.(json|ico|js))$
    static_files: dist/\1
    upload: dist.*\.(json|ico|js)$
  - url: .*
    static_files: dist/index.html
    upload: dist/index.html
    expiration: '0s'